# Generated by Django 4.2.6 on 2023-10-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ucebna',
            fields=[
                ('idUcebna', models.IntegerField(primary_key=True, serialize=False)),
                ('cisloUcebny', models.CharField(max_length=10)),
                ('kapacity', models.IntegerField()),
            ],
        ),
    ]
