# Generated by Django 5.0.1 on 2024-04-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obory',
            fields=[
                ('id_oboru', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_oboru', models.CharField(max_length=100)),
                ('zkratka_oboru', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('heslo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45)),
                ('heslo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Firmy',
            fields=[
                ('id_firmy', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_firmy', models.CharField(max_length=45, verbose_name='Název firmy')),
                ('o_firme', models.CharField(max_length=100, verbose_name='O firmě')),
                ('nazev_prezentace', models.CharField(max_length=100, verbose_name='Název přednášky')),
                ('obory', models.ManyToManyField(blank=True, related_name='firmy', to='myapp.obory')),
            ],
        ),
    ]
