# Generated by Django 4.2.6 on 2023-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucebny',
            fields=[
                ('id_ucebny', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev_ucebny', models.CharField(max_length=10)),
                ('kapacita', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ucebna',
        ),
    ]
