# Generated by Django 5.0.1 on 2024-04-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OboryFirmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_firmy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.firmy')),
                ('id_oboru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.obory')),
            ],
        ),
    ]
