# Generated by Django 5.0.1 on 2024-04-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmy',
            fields=[
                ('id_firmy', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_firmy', models.CharField(max_length=45, verbose_name='Název firmy')),
                ('o_firme', models.CharField(max_length=100, verbose_name='O firmě')),
                ('nazev_prezentace', models.CharField(max_length=100, verbose_name='Název přednášky')),
                ('obory', models.ManyToManyField(blank=True, related_name='firmy', to='myapp.obory')),
            ],
        ),
    ]