# Generated by Django 4.2.6 on 2023-10-19 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ucebny_delete_ucebna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45)),
                ('heslo', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='ucebny',
            name='id_ucebny',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Firmy',
            fields=[
                ('id_firmy', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_firmy', models.CharField(max_length=45)),
                ('o_firme', models.CharField(max_length=100)),
                ('nazev_prezentace', models.CharField(max_length=100)),
                ('ucebna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.ucebny')),
            ],
        ),
    ]
