# Generated by Django 5.0.1 on 2024-04-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_oboryfirmy'),
        ('myapp', '0003_addFirmyAgain'),
    ]

    operations = [
    ]
