# Generated by Django 5.0.1 on 2024-04-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_merge_0002_oboryfirmy_0003_addFirmyAgain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmy',
            name='nazev_firmy',
            field=models.CharField(max_length=45, verbose_name='Název firmy'),
        ),
    ]
