# Generated by Django 4.2.6 on 2024-01-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_firmy_ucebna_delete_ucebny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmy',
            name='nazev_firmy',
            field=models.CharField(max_length=45, verbose_name='Název firmy'),
        ),
        migrations.AlterField(
            model_name='firmy',
            name='nazev_prezentace',
            field=models.CharField(max_length=100, verbose_name='Název přednášky'),
        ),
        migrations.AlterField(
            model_name='firmy',
            name='o_firme',
            field=models.CharField(max_length=100, verbose_name='O firmě'),
        ),
        migrations.CreateModel(
            name='Obory',
            fields=[
                ('id_oboru', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_oboru', models.CharField(max_length=45)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.firmy')),
            ],
        ),
    ]
