# Generated by Django 4.2.6 on 2024-01-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_firmy_nazev_firmy_alter_firmy_nazev_prezentace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obory',
            name='firma',
        ),
    ]
