# Generated by Django 5.0.1 on 2024-01-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_obory_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obory',
            name='id_oboru',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
