# Generated by Django 5.0.1 on 2024-02-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_obory_id_oboru'),
    ]

    operations = [
        migrations.AddField(
            model_name='obory',
            name='firmy',
            field=models.ManyToManyField(blank=True, related_name='obory', to='myapp.firmy'),
        ),
        migrations.AddField(
            model_name='obory',
            name='zkratka_oboru',
            field=models.CharField(default='ZKRATKA_O', max_length=10),
        ),
        migrations.AlterField(
            model_name='obory',
            name='id_oboru',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='obory',
            name='nazev_oboru',
            field=models.CharField(max_length=100),
        ),
    ]
