# Generated by Django 5.0.1 on 2024-02-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_obory_firmy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obory',
            name='firmy',
        ),
        migrations.AddField(
            model_name='firmy',
            name='obory',
            field=models.ManyToManyField(blank=True, related_name='obory', to='myapp.obory'),
        ),
    ]
