# Generated by Django 5.0.1 on 2024-02-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_firmy_obory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmy',
            name='obory',
        ),
    ]
