# Generated by Django 5.0.1 on 2024-02-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_firmy_obory'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmy',
            name='obory',
            field=models.ManyToManyField(blank=True, related_name='firmy', to='myapp.obory'),
        ),
    ]
